"""
Garmin Connect integration service.
Handles authentication, activity fetching, and FIT file parsing.
"""

import io
import json
import zipfile
import tempfile
import os
import sys
import logging
from pathlib import Path
from datetime import datetime, date, timedelta
from typing import List, Dict, Optional
import fitparse
from garminconnect import Garmin as GarminConnectAPI
import garth
from sqlalchemy.orm import Session
from cryptography.fernet import Fernet

from .. import models, crud
from ..core.config import settings

logger = logging.getLogger(__name__)

# Helper function to print, log, and write to debug log file
DEBUG_LOG_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))), ".cursor", "debug.log")

def log_print(message: str, level: str = "info", hypothesis_id: str = None, data: dict = None):
    """Print message, log it, and write to debug log file with timestamp."""
    import json
    from datetime import datetime
    
    # Add timestamp and format message for console output
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    formatted_message = f"[{timestamp}] [GARMIN] {message}"
    
    # Use Python logger (uvicorn will display this in terminal)
    # Format with timestamp so it's visible
    if level == "info":
        logger.info(formatted_message)
    elif level == "warning":
        logger.warning(formatted_message)
    elif level == "error":
        logger.error(formatted_message)
    elif level == "debug":
        logger.debug(formatted_message)
    else:
        logger.info(formatted_message)
    
    # Also print to stdout with flush (for immediate visibility)
    # This ensures logs appear even if uvicorn logging is misconfigured
    print(formatted_message, file=sys.stdout, flush=True)
    
    # Force flush both streams
    sys.stdout.flush()
    sys.stderr.flush()
    
    # Write to debug log file (NDJSON format)
    try:
        log_entry = {
            "timestamp": int(datetime.utcnow().timestamp() * 1000),
            "location": f"garmin_service.py",
            "message": message,
            "level": level,
            "data": data or {},
            "sessionId": "debug-session",
            "runId": "garmin-debug",
        }
        if hypothesis_id:
            log_entry["hypothesisId"] = hypothesis_id
        
        # Ensure directory exists
        log_dir = os.path.dirname(DEBUG_LOG_PATH)
        os.makedirs(log_dir, exist_ok=True)
        
        # Append to debug log file
        with open(DEBUG_LOG_PATH, "a", encoding="utf-8") as f:
            f.write(json.dumps(log_entry, ensure_ascii=False) + "\n")
            f.flush()
    except Exception as e:
        # Don't let debug logging break the app
        pass

# Encryption key (should be in settings)
# Generate a Fernet-compatible key from secret_key
import base64
import hashlib

# Create a 32-byte key from settings.secret_key using SHA-256
key_bytes = hashlib.sha256(settings.secret_key.encode()).digest()
# Fernet requires base64-encoded 32-byte key
ENCRYPTION_KEY = base64.urlsafe_b64encode(key_bytes)
cipher = Fernet(ENCRYPTION_KEY)

# Global cache for garth sessions (in-memory, per-process)
# Key: (user_id, token_hash), Value: (api_instance, timestamp)
_garth_session_cache: Dict[tuple, tuple] = {}


def encrypt_token(token: str) -> str:
    """Encrypt Garmin token for secure storage."""
    return cipher.encrypt(token.encode()).decode()


def decrypt_token(encrypted_token: str) -> str:
    """Decrypt Garmin token from database."""
    return cipher.decrypt(encrypted_token.encode()).decode()


def authenticate_garmin(email: str, password: str) -> Dict[str, any]:
    """
    Authenticate with Garmin Connect and return session token.

    Args:
        email: Garmin Connect email
        password: Garmin Connect password

    Returns:
        Dict with serialized garth session and user info

    Raises:
        Exception: If authentication fails
    """
    # Login with garth (handles OAuth flow)
    garth.login(email, password)

    # Configure garth client
    garth.configure(domain="garmin.com")

    # Use temporary directory for initial login (to get user_id after)
    temp_dir = tempfile.mkdtemp()
    garth.save(temp_dir)

    # Read ONLY OAuth token files (ignore email/password for security)
    session_data = {}
    allowed_files = ["oauth1_token.json", "oauth2_token.json"]
    for filename in os.listdir(temp_dir):
        if filename in allowed_files:
            file_path = os.path.join(temp_dir, filename)
            with open(file_path, "r") as f:
                session_data[filename] = f.read()

    # Clean up temp directory (session will be stored in DB and persistent dir)
    import shutil

    shutil.rmtree(temp_dir)

    if not session_data:
        raise Exception("No session files generated by garth")

    # Configure garth with longer timeout for large syncs (2 years of data)
    garth.configure(timeout=120)

    # Initialize Garmin API (uses garth's global client)
    api = GarminConnectAPI()

    # Verify connection
    user_info = api.get_full_name()

    return {
        "session_data": json.dumps(session_data),  # All garth session files as JSON
        "api": api,
        "user_name": user_info,
    }


def connect_user_garmin(
    db: Session, user_id: int, email: str, password: str
) -> models.User:
    """
    Connect a user's Garmin account.
    Authenticates with Garmin and saves OAuth tokens for future use.
    Also stores encrypted email + password as backup.

    Args:
        db: Database session
        user_id: User ID
        email: Garmin email
        password: Garmin password

    Returns:
        Updated User model

    Raises:
        Exception: If authentication fails
    """
    logger.info(f"Connecting Garmin account for {email}", extra={"user_id": user_id})

    # Configure garth
    garth.configure(timeout=120, domain="garmin.com")

    # Authenticate with Garmin to get OAuth tokens
    # #region agent log
    log_print(f"[GARMIN CONNECT] Logging in with garth for user {user_id}...", hypothesis_id="H1", data={"user_id": user_id, "step": "start_login"})
    # #endregion
    try:
        garth.login(email, password)
        garth.configure(domain="garmin.com")
        # #region agent log
        log_print(f"[GARMIN CONNECT] Login successful", hypothesis_id="H1", data={"user_id": user_id, "step": "login_success"})
        # #endregion
    except Exception as e:
        import traceback
        error_detail = str(e)
        traceback_str = traceback.format_exc()
        logger.error(f"Garmin authentication failed: {error_detail}", exc_info=True)
        log_print(f"[GARMIN CONNECT] [ERROR] Authentication failed: {error_detail}", level="error", hypothesis_id="H1", data={"error": error_detail, "traceback": traceback_str})
        
        # Try to identify specific error types
        if "401" in error_detail or "Unauthorized" in error_detail:
            raise Exception(f"Invalid Garmin credentials (email or password incorrect)")
        elif "429" in error_detail or "rate limit" in error_detail.lower():
            raise Exception(f"Garmin rate limit exceeded. Please try again later.")
        else:
            raise Exception(f"Failed to authenticate with Garmin: {error_detail}")

    # Set up persistent directory for OAuth tokens
    # Use __file__ to reliably get backend directory
    # __file__ is backend/app/services/garmin_service.py
    # We want backend/garmin_tokens (go up 2 levels: services -> app, then up 1 more to backend)
    service_file = os.path.abspath(__file__)  # Full path to this file
    services_dir = os.path.dirname(service_file)  # backend/app/services
    app_dir = os.path.dirname(services_dir)  # backend/app
    backend_dir = os.path.dirname(app_dir)  # backend
    if os.name == 'nt':  # Windows
        persistent_dir = os.path.join(backend_dir, "garmin_tokens")
    else:  # Linux/Docker
        persistent_dir = "/app/garmin_tokens"
    user_token_dir = os.path.join(persistent_dir, f"user_{user_id}")
    os.makedirs(user_token_dir, exist_ok=True)
    # #region agent log
    log_print(f"[GARMIN CONNECT] Service file: {service_file}", hypothesis_id="H2", data={"service_file": service_file})
    log_print(f"[GARMIN CONNECT] Backend dir: {backend_dir}", hypothesis_id="H2", data={"backend_dir": backend_dir})
    log_print(f"[GARMIN CONNECT] Token directory: {user_token_dir}", hypothesis_id="H2", data={"token_dir": user_token_dir, "user_id": user_id})
    log_print(f"[GARMIN CONNECT] Directory exists: {os.path.exists(user_token_dir)}", hypothesis_id="H2", data={"token_dir": user_token_dir, "exists": os.path.exists(user_token_dir)})
    # #endregion

    # Save OAuth tokens to persistent directory
    # #region agent log
    log_print(f"[GARMIN CONNECT] Saving OAuth tokens to {user_token_dir}", hypothesis_id="H3", data={"token_dir": user_token_dir, "step": "before_save"})
    # #endregion
    try:
        garth.save(user_token_dir)
        # #region agent log
        log_print(f"[GARMIN CONNECT] garth.save() completed", hypothesis_id="H3", data={"token_dir": user_token_dir, "step": "save_complete"})
        # #endregion
    except Exception as e:
        # #region agent log
        log_print(f"[GARMIN CONNECT] [ERROR] Failed to save tokens: {str(e)}", level="error", hypothesis_id="H3", data={"token_dir": user_token_dir, "error": str(e)})
        # #endregion
        raise
    
    # Verify files were saved and validate their content
    oauth1_saved = os.path.join(user_token_dir, "oauth1_token.json")
    oauth2_saved = os.path.join(user_token_dir, "oauth2_token.json")
    oauth1_exists = os.path.exists(oauth1_saved)
    oauth2_exists = os.path.exists(oauth2_saved)
    # #region agent log
    log_print(f"[GARMIN CONNECT] Checking token files after save", hypothesis_id="H3", data={"oauth1_exists": oauth1_exists, "oauth2_exists": oauth2_exists, "oauth1_path": oauth1_saved, "oauth2_path": oauth2_saved})
    # #endregion
    
    if oauth1_exists and oauth2_exists:
        oauth1_size = os.path.getsize(oauth1_saved)
        oauth2_size = os.path.getsize(oauth2_saved)
        
        # Validate JSON content of both files
        oauth1_valid = False
        oauth2_valid = False
        try:
            with open(oauth1_saved, "r") as f:
                oauth1_data = json.load(f)
                oauth1_valid = isinstance(oauth1_data, dict) and len(oauth1_data) > 0
                log_print(f"[GARMIN CONNECT] oauth1_token.json is valid JSON: {oauth1_valid}", hypothesis_id="H3", data={"oauth1_valid": oauth1_valid, "oauth1_keys": list(oauth1_data.keys()) if oauth1_valid else []})
        except Exception as e:
            log_print(f"[GARMIN CONNECT] [ERROR] oauth1_token.json is invalid JSON: {str(e)}", level="error", hypothesis_id="H3")
        
        try:
            with open(oauth2_saved, "r") as f:
                oauth2_data = json.load(f)
                oauth2_valid = isinstance(oauth2_data, dict) and len(oauth2_data) > 0
                log_print(f"[GARMIN CONNECT] oauth2_token.json is valid JSON: {oauth2_valid}", hypothesis_id="H3", data={"oauth2_valid": oauth2_valid, "oauth2_keys": list(oauth2_data.keys()) if oauth2_valid else []})
        except Exception as e:
            log_print(f"[GARMIN CONNECT] [ERROR] oauth2_token.json is invalid JSON: {str(e)}", level="error", hypothesis_id="H3")
        
        if oauth1_size > 0 and oauth2_size > 0 and oauth1_valid and oauth2_valid:
            log_print(f"[GARMIN CONNECT] [OK] Tokens saved and validated successfully: oauth1={oauth1_size} bytes, oauth2={oauth2_size} bytes", hypothesis_id="H3", data={"oauth1_size": oauth1_size, "oauth2_size": oauth2_size})
        else:
            error_msg = f"Token files saved but validation failed: oauth1_size={oauth1_size}, oauth2_size={oauth2_size}, oauth1_valid={oauth1_valid}, oauth2_valid={oauth2_valid}"
            log_print(f"[GARMIN CONNECT] [ERROR] {error_msg}", level="error", hypothesis_id="H3")
            raise Exception(error_msg)
    else:
        error_msg = f"Token files not found after save: oauth1_exists={oauth1_exists}, oauth2_exists={oauth2_exists}"
        log_print(f"[GARMIN CONNECT] [ERROR] {error_msg}", level="error", hypothesis_id="H3", data={"oauth1_exists": oauth1_exists, "oauth2_exists": oauth2_exists})
        if os.path.exists(user_token_dir):
            all_files = os.listdir(user_token_dir)
            log_print(f"[GARMIN CONNECT] Files in directory: {all_files}", hypothesis_id="H3", data={"files": all_files})
        else:
            log_print(f"[GARMIN CONNECT] Directory does not exist: {user_token_dir}", level="error", hypothesis_id="H3")
        raise Exception(error_msg)

    # Remove email/password files for security (keep only OAuth tokens)
    import shutil
    allowed_files = ["oauth1_token.json", "oauth2_token.json"]
    for filename in os.listdir(user_token_dir):
        if filename not in allowed_files:
            file_path = os.path.join(user_token_dir, filename)
            os.remove(file_path)
            log_print(f"[GARMIN CONNECT] Removed {filename} for security")
        else:
            # Verify file has content
            file_path = os.path.join(user_token_dir, filename)
            size = os.path.getsize(file_path)
            log_print(f"[GARMIN CONNECT] Saved {filename} ({size} bytes)")

    # Verify the connection works by making a test API call
    try:
        api = GarminConnectAPI()
        user_name = api.get_full_name()
        log_print(f"[GARMIN CONNECT] Verified connection for user: {user_name}")
    except Exception as e:
        logger.warning(f"Could not verify Garmin connection: {str(e)}", exc_info=True)
        log_print(f"[GARMIN CONNECT] [WARNING] Could not verify connection: {str(e)}")
        # Continue anyway - tokens are saved, verification can happen during sync

    # Store email + encrypted password as backup (for re-authentication if tokens expire)
    credentials = json.dumps({"email": email, "password": password})
    encrypted_credentials = encrypt_token(credentials)

    # Update user
    user = crud.get_user_by_id(db, user_id)
    user.garmin_email = email
    user.garmin_token = encrypted_credentials
    user.garmin_connected_at = datetime.utcnow()

    db.commit()
    db.refresh(user)

    logger.info(f"Garmin account connected successfully for user {user_id}")
    return user


def get_user_garmin_api(db: Session, user_id: int) -> GarminConnectAPI:
    """
    Get authenticated Garmin API for a user.
    Tries to restore existing session first, falls back to login if needed.

    Args:
        db: Database session
        user_id: User ID

    Returns:
        Authenticated GarminConnectAPI instance

    Raises:
        Exception: If user not connected or credentials invalid
    """
    user = crud.get_user_by_id(db, user_id)

    if not user.garmin_token or not user.garmin_email:
        raise Exception("User has not connected Garmin account")

    # Configure garth with longer timeout for large syncs (2 years of data)
    garth.configure(timeout=120)

    # Persistent directory for OAuth tokens
    # Use same path calculation as connect_user_garmin to ensure consistency
    # Use __file__ to reliably get backend directory
    # __file__ is backend/app/services/garmin_service.py
    # We want backend/garmin_tokens (go up 2 levels: services -> app, then up 1 more to backend)
    service_file = os.path.abspath(__file__)  # Full path to this file
    services_dir = os.path.dirname(service_file)  # backend/app/services
    app_dir = os.path.dirname(services_dir)  # backend/app
    backend_dir = os.path.dirname(app_dir)  # backend
    if os.name == 'nt':  # Windows
        persistent_dir = os.path.join(backend_dir, "garmin_tokens")
    else:  # Linux/Docker
        persistent_dir = "/app/garmin_tokens"
    user_token_dir = os.path.join(persistent_dir, f"user_{user_id}")
    os.makedirs(user_token_dir, exist_ok=True)
    log_print(f"[GARMIN SYNC] Service file: {service_file}")
    log_print(f"[GARMIN SYNC] Backend dir: {backend_dir}")
    log_print(f"[GARMIN SYNC] Token directory: {user_token_dir}")
    log_print(f"[GARMIN SYNC] Directory exists: {os.path.exists(user_token_dir)}")

    # Try to restore existing session first
    oauth1_path = os.path.join(user_token_dir, "oauth1_token.json")
    oauth2_path = os.path.join(user_token_dir, "oauth2_token.json")
    
    oauth1_exists = os.path.exists(oauth1_path)
    oauth2_exists = os.path.exists(oauth2_path)
    # #region agent log
    log_print(f"[GARMIN SYNC] Checking for tokens:", hypothesis_id="H5", data={"step": "check_tokens"})
    log_print(f"[GARMIN SYNC]   oauth1_path: {oauth1_path}", hypothesis_id="H5", data={"oauth1_path": oauth1_path})
    log_print(f"[GARMIN SYNC]   oauth1 exists: {oauth1_exists}", hypothesis_id="H5", data={"oauth1_exists": oauth1_exists})
    log_print(f"[GARMIN SYNC]   oauth2_path: {oauth2_path}", hypothesis_id="H5", data={"oauth2_path": oauth2_path})
    log_print(f"[GARMIN SYNC]   oauth2 exists: {oauth2_exists}", hypothesis_id="H5", data={"oauth2_exists": oauth2_exists})
    if os.path.exists(user_token_dir):
        all_files = os.listdir(user_token_dir)
        log_print(f"[GARMIN SYNC]   Files in directory: {all_files}", hypothesis_id="H5", data={"files": all_files})
    # #endregion
    
    # Validate JSON content if files exist
    if oauth1_exists and oauth2_exists:
        oauth1_valid = False
        oauth2_valid = False
        try:
            with open(oauth1_path, "r") as f:
                oauth1_data = json.load(f)
                oauth1_valid = isinstance(oauth1_data, dict) and len(oauth1_data) > 0
                log_print(f"[GARMIN SYNC] oauth1_token.json is valid: {oauth1_valid}", hypothesis_id="H5", data={"oauth1_valid": oauth1_valid})
        except Exception as e:
            log_print(f"[GARMIN SYNC] [ERROR] oauth1_token.json is invalid JSON: {str(e)}", level="error", hypothesis_id="H5")
        
        try:
            with open(oauth2_path, "r") as f:
                oauth2_data = json.load(f)
                oauth2_valid = isinstance(oauth2_data, dict) and len(oauth2_data) > 0
                log_print(f"[GARMIN SYNC] oauth2_token.json is valid: {oauth2_valid}", hypothesis_id="H5", data={"oauth2_valid": oauth2_valid})
        except Exception as e:
            log_print(f"[GARMIN SYNC] [ERROR] oauth2_token.json is invalid JSON: {str(e)}", level="error", hypothesis_id="H5")
        
        if not (oauth1_valid and oauth2_valid):
            log_print(f"[GARMIN SYNC] [ERROR] Token files exist but are invalid, will re-authenticate", level="error", hypothesis_id="H5")
            oauth1_exists = False  # Force re-authentication
            oauth2_exists = False
    
    if oauth1_exists and oauth2_exists:
        try:
            # #region agent log
            log_print(f"[GARMIN SYNC] Attempting to restore existing session from {user_token_dir}", hypothesis_id="H5", data={"step": "try_resume", "token_dir": user_token_dir})
            # #endregion
            
            # Clear any existing garth state before resuming
            try:
                # Try to logout/reset garth state if possible
                if hasattr(garth, 'logout'):
                    try:
                        garth.logout()
                    except:
                        pass
            except:
                pass
            
            # Configure and resume
            # IMPORTANT: garth uses a global client, so we need to ensure it's properly configured
            # According to garth documentation, resume() should be called AFTER configure()
            # and it will create the client if tokens exist
            
            # CRITICAL FIX: Follow the same pattern as garmin_health_service.py
            # which successfully uses garth.resume() + garth.configure() + GarminConnectAPI()
            # The key difference is the ORDER: resume() first, then configure()
            
            log_print(f"[GARMIN SYNC] Calling garth.resume() with path: {user_token_dir}", hypothesis_id="H5", data={"token_dir": user_token_dir, "step": "before_resume"})
            
            try:
                # Resume session - this loads tokens from files
                # Note: In some garth versions, resume() may not create client immediately
                garth.resume(user_token_dir)
                log_print(f"[GARMIN SYNC] garth.resume() completed", hypothesis_id="H5", data={"step": "resume_complete"})
            except Exception as resume_error:
                log_print(f"[GARMIN SYNC] [ERROR] garth.resume() raised exception: {str(resume_error)}", level="error", hypothesis_id="H5", data={"error": str(resume_error)})
                raise
            
            # Configure AFTER resume (same pattern as garmin_health_service.py)
            log_print(f"[GARMIN SYNC] Configuring garth after resume...", hypothesis_id="H5", data={"step": "configure_after_resume"})
            garth.configure(domain="garmin.com", timeout=120)
            
            # Check if client exists - it should be created by now
            client_after = getattr(garth, 'client', None)
            log_print(f"[GARMIN SYNC] garth.client after resume+configure: {client_after is not None}", hypothesis_id="H5", data={"client_exists": client_after is not None})
            
            # If client still doesn't exist, this is a critical issue
            # In this case, we'll proceed anyway and let GarminConnectAPI() handle it
            # because GarminConnectAPI() might create the client internally
            if not client_after:
                log_print(f"[GARMIN SYNC] [WARNING] garth.client is None after resume+configure, but proceeding - GarminConnectAPI() may create it", level="warning", hypothesis_id="H5")
            
            # #region agent log
            log_print(f"[GARMIN SYNC] garth.resume() completed", hypothesis_id="H5", data={"step": "resume_complete"})
            # #endregion
            
            # Verify garth has valid OAuth state before creating API
            try:
                # Check if garth client has tokens
                if hasattr(garth, 'client') and garth.client:
                    has_oauth1 = hasattr(garth.client, 'oauth1_token') and garth.client.oauth1_token
                    has_oauth2 = hasattr(garth.client, 'oauth2_token') and garth.client.oauth2_token
                    log_print(f"[GARMIN SYNC] Garth client state: oauth1={has_oauth1}, oauth2={has_oauth2}", hypothesis_id="H5", data={"has_oauth1": has_oauth1, "has_oauth2": has_oauth2})
                    
                    if not (has_oauth1 and has_oauth2):
                        raise Exception("Garth client does not have valid OAuth tokens after resume")
            except AttributeError:
                # garth.client might not have these attributes, continue anyway
                log_print(f"[GARMIN SYNC] Could not verify garth client OAuth state (not critical)", hypothesis_id="H5")
            
            # Verify garth client state is preserved before creating API
            try:
                # Force garth to use the resumed session
                if hasattr(garth, 'client') and garth.client:
                    # Verify tokens are still there
                    has_oauth1_after = hasattr(garth.client, 'oauth1_token') and garth.client.oauth1_token
                    has_oauth2_after = hasattr(garth.client, 'oauth2_token') and garth.client.oauth2_token
                    log_print(f"[GARMIN SYNC] Before API creation - oauth1={has_oauth1_after}, oauth2={has_oauth2_after}", hypothesis_id="H5", data={"has_oauth1": has_oauth1_after, "has_oauth2": has_oauth2_after})
                    
                    if not has_oauth1_after:
                        log_print(f"[GARMIN SYNC] [ERROR] oauth1_token lost after resume!", level="error", hypothesis_id="H5")
                        raise Exception("OAuth1 token not found in garth.client after resume")
            except AttributeError:
                log_print(f"[GARMIN SYNC] Could not verify garth client state before API creation", level="warning", hypothesis_id="H5")
            
            # CRITICAL: Verify garth.client has oauth1_token before creating API
            # GarminConnectAPI() uses garth.client internally, so it must have tokens
            try:
                if hasattr(garth, 'client') and garth.client:
                    # Check oauth1_token directly
                    oauth1_token = getattr(garth.client, 'oauth1_token', None)
                    oauth2_token = getattr(garth.client, 'oauth2_token', None)
                    log_print(f"[GARMIN SYNC] Direct token check - oauth1_token exists: {oauth1_token is not None}, oauth2_token exists: {oauth2_token is not None}", hypothesis_id="H5", data={"has_oauth1": oauth1_token is not None, "has_oauth2": oauth2_token is not None})
                    
                    if oauth1_token is None:
                        # Try to inspect what's in garth.client
                        client_attrs = dir(garth.client)
                        log_print(f"[GARMIN SYNC] [ERROR] oauth1_token is None! garth.client attributes: {[a for a in client_attrs if not a.startswith('_')]}", level="error", hypothesis_id="H5")
                        raise Exception("OAuth1 token is None in garth.client after resume - cannot create API")
            except Exception as e:
                log_print(f"[GARMIN SYNC] [ERROR] Failed to verify tokens before API creation: {str(e)}", level="error", hypothesis_id="H5")
                raise
            
            # Verify session is valid by making a test API call
            log_print(f"[GARMIN SYNC] Creating GarminConnectAPI instance...", hypothesis_id="H5", data={"step": "create_api"})
            api = GarminConnectAPI()
            
            # CRITICAL FIX: GarminConnectAPI() creates api.garth but NOT api.garth.client
            # Also, api.garth.connectapi() uses api.garth.oauth1_token directly, not api.garth.client.oauth1_token
            # We need to:
            # 1. Assign garth.client to api.garth.client
            # 2. Copy tokens to api.garth directly
            log_print(f"[GARMIN SYNC] [FIX] Assigning garth.client to api.garth.client and copying tokens to api.garth...", hypothesis_id="H5", data={"step": "assign_client_fix"})
            try:
                if hasattr(garth, 'client') and garth.client:
                    if hasattr(api, 'garth'):
                        # Step 1: Assign the global garth.client to api.garth.client
                        api.garth.client = garth.client
                        log_print(f"[GARMIN SYNC] [FIX] Step 1: Assigned garth.client to api.garth.client", hypothesis_id="H5", data={"step": "assign_client"})
                        
                        # Step 2: Copy tokens directly to api.garth (because connectapi() uses api.garth.oauth1_token)
                        # CRITICAL: This MUST be done because api.garth.connectapi() -> self.request() checks self.oauth1_token
                        if hasattr(garth.client, 'oauth1_token') and garth.client.oauth1_token:
                            api.garth.oauth1_token = garth.client.oauth1_token
                            log_print(f"[GARMIN SYNC] [FIX] Step 2: Copied oauth1_token to api.garth", hypothesis_id="H5", data={"step": "copy_oauth1_to_garth"})
                        if hasattr(garth.client, 'oauth1_token_secret') and garth.client.oauth1_token_secret:
                            api.garth.oauth1_token_secret = garth.client.oauth1_token_secret
                        if hasattr(garth.client, 'oauth2_token') and garth.client.oauth2_token:
                            api.garth.oauth2_token = garth.client.oauth2_token
                        
                        # Verify both
                        has_client_oauth1 = hasattr(api.garth, 'client') and hasattr(api.garth.client, 'oauth1_token') and api.garth.client.oauth1_token is not None
                        has_garth_oauth1 = hasattr(api.garth, 'oauth1_token') and api.garth.oauth1_token is not None
                        log_print(f"[GARMIN SYNC] [FIX] Verification - api.garth.client.oauth1_token: {has_client_oauth1}, api.garth.oauth1_token: {has_garth_oauth1}", hypothesis_id="H5", data={"client_oauth1": has_client_oauth1, "garth_oauth1": has_garth_oauth1})
                        
                        if not has_garth_oauth1:
                            log_print(f"[GARMIN SYNC] [ERROR] api.garth.oauth1_token is still None after copy! This will cause get_activities() to fail!", level="error", hypothesis_id="H5")
                        
                        if not has_garth_oauth1:
                            log_print(f"[GARMIN SYNC] [ERROR] api.garth.oauth1_token is still None after copy!", level="error", hypothesis_id="H5")
                    else:
                        log_print(f"[GARMIN SYNC] [ERROR] api.garth doesn't exist", level="error", hypothesis_id="H5")
                else:
                    log_print(f"[GARMIN SYNC] [ERROR] garth.client doesn't exist to assign", level="error", hypothesis_id="H5")
            except Exception as assign_error:
                import traceback
                log_print(f"[GARMIN SYNC] [ERROR] Failed to assign/copy tokens: {str(assign_error)}", level="error", hypothesis_id="H5", data={"error": str(assign_error), "traceback": traceback.format_exc()})
            
            # Verify garth state is still there after API creation - DETAILED DIAGNOSTIC
            log_print(f"[GARMIN SYNC] [DIAGNOSTIC] Verifying state after GarminConnectAPI() creation...", hypothesis_id="H5", data={"step": "after_api_creation_diagnostic"})
            try:
                global_client_exists = hasattr(garth, 'client') and garth.client is not None
                global_oauth1_exists = global_client_exists and hasattr(garth.client, 'oauth1_token') and garth.client.oauth1_token is not None
                global_oauth2_exists = global_client_exists and hasattr(garth.client, 'oauth2_token') and garth.client.oauth2_token is not None
                global_client_id = id(garth.client) if global_client_exists else None
                
                log_print(f"[GARMIN SYNC] [DIAGNOSTIC] Global garth.client state:", hypothesis_id="H5", data={
                    "exists": global_client_exists,
                    "has_oauth1": global_oauth1_exists,
                    "has_oauth2": global_oauth2_exists,
                    "client_id": global_client_id
                })
                
                # Check api.garth.client
                api_garth_exists = hasattr(api, 'garth')
                api_client_exists = api_garth_exists and hasattr(api.garth, 'client') and api.garth.client is not None
                api_oauth1_exists = api_client_exists and hasattr(api.garth.client, 'oauth1_token') and api.garth.client.oauth1_token is not None
                api_oauth2_exists = api_client_exists and hasattr(api.garth.client, 'oauth2_token') and api.garth.client.oauth2_token is not None
                api_client_id = id(api.garth.client) if api_client_exists else None
                
                log_print(f"[GARMIN SYNC] [DIAGNOSTIC] api.garth.client state:", hypothesis_id="H5", data={
                    "garth_exists": api_garth_exists,
                    "client_exists": api_client_exists,
                    "has_oauth1": api_oauth1_exists,
                    "has_oauth2": api_oauth2_exists,
                    "client_id": api_client_id
                })
                
                # Check if they are the same object
                if global_client_exists and api_client_exists:
                    same_object = garth.client is api.garth.client
                    log_print(f"[GARMIN SYNC] [DIAGNOSTIC] Are garth.client and api.garth.client the same object? {same_object}", hypothesis_id="H5", data={
                        "same_object": same_object,
                        "global_id": global_client_id,
                        "api_id": api_client_id
                    })
                    
                    if not same_object:
                        log_print(f"[GARMIN SYNC] [DIAGNOSTIC] [WARNING] Different objects! GarminConnectAPI() created its own client", level="warning", hypothesis_id="H5")
                    
                    if global_oauth1_exists and not api_oauth1_exists:
                        log_print(f"[GARMIN SYNC] [DIAGNOSTIC] [WARNING] Global has oauth1_token but api.garth.client does not!", level="warning", hypothesis_id="H5")
            except Exception as e:
                import traceback
                log_print(f"[GARMIN SYNC] [DIAGNOSTIC] Error verifying state after API creation: {str(e)}", level="error", hypothesis_id="H5", data={"error": str(e), "traceback": traceback.format_exc()})
            
            log_print(f"[GARMIN SYNC] Testing API with get_full_name()...", hypothesis_id="H5", data={"step": "test_api"})
            user_name = api.get_full_name()  # Test call
            # #region agent log
            log_print(f"[GARMIN SYNC] [OK] Session restored successfully for user: {user_name}", hypothesis_id="H5", data={"step": "restore_success", "user_name": user_name})
            # #endregion
            return api
        except Exception as e:
            import traceback
            traceback_str = traceback.format_exc()
            # #region agent log
            log_print(f"[GARMIN SYNC] [ERROR] Failed to restore session: {str(e)}, will re-authenticate", level="error", hypothesis_id="H5", data={"step": "restore_failed", "error": str(e), "traceback": traceback_str})
            # #endregion
            
            # Clean up garth state on failure
            try:
                if hasattr(garth, 'logout'):
                    garth.logout()
            except:
                pass

    # If restore failed or no tokens exist, do fresh login
    log_print(f"[GARMIN SYNC] Performing fresh login...", hypothesis_id="H5", data={"step": "fresh_login"})
    
    # Decrypt credentials
    try:
        credentials_json = decrypt_token(user.garmin_token)
        credentials = json.loads(credentials_json)
        email = credentials["email"]
        password = credentials["password"]
        log_print(f"[GARMIN SYNC] Credentials decrypted for user: {email}", hypothesis_id="H5")
    except Exception as e:
        log_print(f"[GARMIN SYNC] [ERROR] Failed to decrypt credentials: {str(e)}", level="error", hypothesis_id="H5")
        raise Exception(f"Failed to decrypt Garmin credentials: {str(e)}")

    # Use garth directly to ensure session is saved correctly
    log_print(f"[GARMIN SYNC] Logging in with garth...", hypothesis_id="H5", data={"step": "garth_login"})
    garth.login(email, password)
    garth.configure(domain="garmin.com", timeout=120)
    log_print(f"[GARMIN SYNC] Login successful", hypothesis_id="H5", data={"step": "login_success"})

    # Save OAuth tokens to persistent directory for Celery workers
    # Use same path calculation as connect_user_garmin to ensure consistency
    # Use __file__ to reliably get backend directory
    service_file = os.path.abspath(__file__)
    services_dir = os.path.dirname(service_file)
    app_dir = os.path.dirname(services_dir)
    backend_dir = os.path.dirname(app_dir)
    if os.name == 'nt':  # Windows
        persistent_dir = os.path.join(backend_dir, "garmin_tokens")
    else:  # Linux/Docker
        persistent_dir = "/app/garmin_tokens"
    user_token_dir = os.path.join(persistent_dir, f"user_{user_id}")
    os.makedirs(user_token_dir, exist_ok=True)
    log_print(f"[GARMIN SYNC] Saving new tokens to: {user_token_dir}", hypothesis_id="H5", data={"step": "save_new_tokens", "token_dir": user_token_dir})

    # Save garth session directly to user's persistent directory
    log_print(f"[GARMIN SYNC] Saving session to {user_token_dir}", hypothesis_id="H5")
    try:
        garth.save(user_token_dir)
        log_print(f"[GARMIN SYNC] garth.save() completed", hypothesis_id="H5", data={"step": "save_complete"})
        
        # Verify tokens were saved
        oauth1_new = os.path.join(user_token_dir, "oauth1_token.json")
        oauth2_new = os.path.join(user_token_dir, "oauth2_token.json")
        if os.path.exists(oauth1_new) and os.path.exists(oauth2_new):
            oauth1_size = os.path.getsize(oauth1_new)
            oauth2_size = os.path.getsize(oauth2_new)
            log_print(f"[GARMIN SYNC] New tokens saved: oauth1={oauth1_size} bytes, oauth2={oauth2_size} bytes", hypothesis_id="H5", data={"oauth1_size": oauth1_size, "oauth2_size": oauth2_size})
        else:
            log_print(f"[GARMIN SYNC] [WARNING] Token files not found after save", level="warning", hypothesis_id="H5")
    except Exception as e:
        log_print(f"[GARMIN SYNC] [ERROR] Failed to save tokens: {str(e)}", level="error", hypothesis_id="H5")
        raise Exception(f"Failed to save OAuth tokens after fresh login: {str(e)}")

    # Remove email/password files for security (keep only OAuth tokens)
    import shutil

    allowed_files = ["oauth1_token.json", "oauth2_token.json"]
    for filename in os.listdir(user_token_dir):
        if filename not in allowed_files:
            file_path = os.path.join(user_token_dir, filename)
            os.remove(file_path)
            log_print(f"[GARMIN SYNC] Removed {filename} for security")
        else:
            # Verify file has content
            file_path = os.path.join(user_token_dir, filename)
            size = os.path.getsize(file_path)
            log_print(f"[GARMIN SYNC] Kept {filename} ({size} bytes)")

    # Now create GarminConnectAPI using the authenticated garth session
    api = GarminConnectAPI()
    
    # CRITICAL FIX: Assign garth.client to api.garth.client AND copy tokens to api.garth
    if hasattr(garth, 'client') and garth.client and hasattr(api, 'garth'):
        api.garth.client = garth.client
        # Also copy tokens to api.garth directly (connectapi() uses api.garth.oauth1_token)
        if hasattr(garth.client, 'oauth1_token'):
            api.garth.oauth1_token = garth.client.oauth1_token
        if hasattr(garth.client, 'oauth1_token_secret'):
            api.garth.oauth1_token_secret = garth.client.oauth1_token_secret
        if hasattr(garth.client, 'oauth2_token'):
            api.garth.oauth2_token = garth.client.oauth2_token
        log_print(f"[GARMIN SYNC] [FIX] Assigned garth.client to api.garth.client and copied tokens to api.garth (fresh login)", hypothesis_id="H5")

    return api


def parse_fit_file(fit_data: bytes, activity_id: str) -> Dict[str, any]:
    """
    Parse FIT file and extract metrics (adapted from your script).

    Args:
        fit_data: Raw FIT file bytes
        activity_id: Activity ID for reference

    Returns:
        Dict with extracted metrics
    """
    fitfile = fitparse.FitFile(io.BytesIO(fit_data))

    # --- Data Extraction from FIT file ---

    # The 'session' message contains aggregated data for the entire workout.
    # This is much more efficient than iterating through every 'record' message.
    session_data = {}
    for record in fitfile.get_messages("session"):
        session_data = {field.name: field.value for field in record}
        break  # There should only be one session message

    if not session_data:
        # Fallback if no session data is found
        return {"sport_type": "unknown"}

    # --- Map Session Data to our Schema ---

    # Cadence: Garmin reports "strides per minute" (one leg). We want "steps per minute" (both legs).
    # So, we multiply by 2.
    avg_cadence_spm = session_data.get("avg_running_cadence")
    avg_cadence = int(avg_cadence_spm * 2) if avg_cadence_spm else None

    max_cadence_spm = session_data.get("max_running_cadence")
    max_cadence = int(max_cadence_spm * 2) if max_cadence_spm else None

    # Vertical Oscillation (in mm, we convert to cm)
    avg_vo_mm = session_data.get("avg_vertical_oscillation")
    avg_vertical_oscillation = round(avg_vo_mm / 10, 2) if avg_vo_mm else None

    # Stance Time (in ms)
    avg_stance_time = (
        round(session_data.get("avg_stance_time"), 1)
        if session_data.get("avg_stance_time")
        else None
    )

    # Stride Length (in mm, we convert to m)
    avg_stride_length_mm = session_data.get("avg_step_length")
    avg_stride_length = (
        round(avg_stride_length_mm / 1000, 2) if avg_stride_length_mm else None
    )

    # Leg Spring Stiffness (kN/m)
    avg_leg_spring_stiffness = session_data.get("avg_leg_spring_stiffness")

    # Ground Contact Time Balance (as a percentage, left foot)
    # Try multiple field names as Garmin uses different names across devices
    avg_gct_balance = (
        session_data.get("avg_stance_time_percent_left")
        or session_data.get("stance_time_balance")
        or session_data.get("avg_left_torso_angle")
        or None
    )
    # If we have balance, ensure it's in the 0-100 range
    if avg_gct_balance and avg_gct_balance > 1:
        avg_gct_balance = avg_gct_balance  # Already percentage
    elif avg_gct_balance:
        avg_gct_balance = avg_gct_balance * 100  # Convert decimal to percentage

    # --- Detailed Records for Charts ---
    # We still iterate through records to get timeseries data for charts.
    records = []
    record_fields = [
        "timestamp",
        "heart_rate",
        "power",
        "enhanced_altitude",
        "distance",
        "speed",
    ]
    for record in fitfile.get_messages("record"):
        data = {
            field.name: field.value for field in record if field.name in record_fields
        }
        if "timestamp" in data and data["timestamp"]:
            records.append(data)

    # --- Final Data Structure ---
    return {
        "sport_type": session_data.get("sport", "running"),
        "start_time": session_data.get("start_time"),
        "duration_seconds": int(session_data.get("total_timer_time", 0)),
        "distance_meters": round(session_data.get("total_distance", 0.0), 2),
        "avg_pace": (
            session_data.get("total_timer_time", 0)
            / (session_data.get("total_distance", 1) / 1000)
            if session_data.get("total_distance")
            else None
        ),
        "avg_heart_rate": session_data.get("avg_heart_rate"),
        "max_heart_rate": session_data.get("max_heart_rate"),
        "avg_power": session_data.get("avg_power"),
        "elevation_gain": session_data.get("total_ascent"),
        # Running Dynamics
        "avg_cadence": avg_cadence,
        "max_cadence": max_cadence,
        "avg_vertical_oscillation": avg_vertical_oscillation,
        "avg_stance_time": avg_stance_time,
        "avg_stride_length": avg_stride_length,
        "avg_leg_spring_stiffness": avg_leg_spring_stiffness,
        "left_right_balance": avg_gct_balance,
        # Timeseries data for charts
        "records": records,
    }


def sync_user_zones_and_profile(
    db: Session, user_id: int, api: GarminConnectAPI
) -> None:
    """
    Sync HR zones, power zones, and athlete profile data from Garmin.

    Args:
        db: Database session
        user_id: User ID
        api: Authenticated Garmin API instance
    """
    try:
        user = crud.get_user_by_id(db, user_id)

        # Get user profile (height, weight, etc)
        print("[ZONES] Fetching user profile...")
        try:
            profile_data = api.get_user_profile()
            print(
                f"[ZONES] User profile data keys: {list(profile_data.keys()) if profile_data else 'None'}"
            )

            # Log full userData for debugging
            if profile_data and "userData" in profile_data:
                print(
                    f"[ZONES] Full userData keys: {list(profile_data['userData'].keys())}"
                )
                print(
                    f"[ZONES] Sample userData (first 15 fields): {dict(list(profile_data['userData'].items())[:15])}"
                )

            # Update user profile with Garmin data
            # The actual data is nested in 'userData'
            if profile_data and "userData" in profile_data:
                user_data = profile_data["userData"]

                # Height in cm
                if "height" in user_data and user_data["height"]:
                    user.height_cm = user_data["height"]
                    print(f"[ZONES] Updated height: {user.height_cm} cm")

                # Weight in kg (Garmin returns weight in grams)
                if "weight" in user_data and user_data["weight"]:
                    user.weight_kg = user_data["weight"] / 1000
                    print(f"[ZONES] Updated weight: {user.weight_kg} kg")

                # Date of birth
                if "birthDate" in user_data and user_data["birthDate"]:
                    try:
                        from datetime import datetime

                        user.birth_date = datetime.strptime(
                            user_data["birthDate"], "%Y-%m-%d"
                        ).date()
                        print(f"[ZONES] Updated birth date: {user.birth_date}")
                    except:
                        pass

                # Gender
                if "gender" in user_data and user_data["gender"]:
                    user.gender = user_data["gender"].lower()
                    print(f"[ZONES] Updated gender: {user.gender}")

                # VO2 Max Running
                if "vo2MaxRunning" in user_data and user_data["vo2MaxRunning"]:
                    user.vo2_max = user_data["vo2MaxRunning"]
                    print(f"[ZONES] Updated VO2 Max: {user.vo2_max} ml/kg/min")

                # Lactate Threshold HR (can be used as a proxy for threshold HR)
                if (
                    "lactateThresholdHeartRate" in user_data
                    and user_data["lactateThresholdHeartRate"]
                ):
                    # This is actually a good estimate for max HR in many cases
                    # Store it but don't overwrite if user has a custom max HR
                    if not user.max_heart_rate:
                        user.max_heart_rate = user_data["lactateThresholdHeartRate"]
                        print(
                            f"[ZONES] Updated max HR from lactate threshold: {user.max_heart_rate} bpm"
                        )

                db.commit()
                print("[ZONES] User profile basic data updated successfully")
        except Exception as e:
            print(f"[ZONES] Could not fetch user profile: {e}")
            import traceback

            traceback.print_exc()
            profile_data = {}

        # Sync health metrics (HRV, sleep, stress, body battery, etc.)
        print("[ZONES] Syncing health metrics...")
        try:
            from .health_sync_service import (
                sync_health_metrics,
                get_latest_health_metric,
            )
            from .. import models

            # Determine days to sync based on whether we have health metrics
            user = crud.get_user_by_id(db, user_id)

            # Check if user has ANY health metrics from Garmin
            existing_health = (
                db.query(models.HealthMetric)
                .filter(
                    models.HealthMetric.user_id == user_id,
                    models.HealthMetric.source == "garmin",
                )
                .first()
            )

            is_first_health_sync = existing_health is None

            if is_first_health_sync:
                # First sync: get 2 years of health data
                health_days = 730
                print(
                    f"[ZONES] First health sync: pulling {health_days} days of health metrics"
                )
            else:
                # Incremental: just update today and yesterday (data doesn't change beyond that)
                health_days = 2
                print(
                    f"[ZONES] Incremental sync: pulling {health_days} days of health metrics"
                )

            health_metrics = sync_health_metrics(
                api, user_id, db, days_back=health_days
            )

            # Update user's resting HR from most recent health metric
            latest_health = get_latest_health_metric(user_id, db)
            if latest_health and latest_health.resting_hr_bpm:
                user.resting_heart_rate = latest_health.resting_hr_bpm
                print(
                    f"[ZONES] Updated resting HR from health data: {user.resting_heart_rate} bpm"
                )

            db.commit()
            print(f"[ZONES] Health metrics sync completed: {len(health_metrics)} days")
        except Exception as e:
            print(f"[ZONES] Could not sync health metrics: {e}")
            import traceback

            traceback.print_exc()

        # Note: get_user_settings() doesn't exist in garminconnect library
        # All the data we need is already obtained from:
        # - userData for profile (height, weight, VO2 max, lactate threshold HR)
        # - health metrics for resting HR
        # So we skip this section

        # Try to get heart rate zones
        print("[ZONES] Fetching HR zones...")
        hr_zones = []
        try:
            # Calculate based on max HR if available
            if user.max_heart_rate:
                max_hr = user.max_heart_rate
                hr_zones = [
                    {
                        "zone": 1,
                        "name": "Z1",
                        "min": int(max_hr * 0.50),
                        "max": int(max_hr * 0.60),
                    },
                    {
                        "zone": 2,
                        "name": "Z2",
                        "min": int(max_hr * 0.60),
                        "max": int(max_hr * 0.70),
                    },
                    {
                        "zone": 3,
                        "name": "Z3",
                        "min": int(max_hr * 0.70),
                        "max": int(max_hr * 0.80),
                    },
                    {
                        "zone": 4,
                        "name": "Z4",
                        "min": int(max_hr * 0.80),
                        "max": int(max_hr * 0.90),
                    },
                    {
                        "zone": 5,
                        "name": "Z5",
                        "min": int(max_hr * 0.90),
                        "max": int(max_hr * 1.00),
                    },
                ]
                print(f"[ZONES] Calculated HR zones from max HR: {hr_zones}")

            if hr_zones:
                user.hr_zones = hr_zones
                print(f"[ZONES] HR zones saved: {len(hr_zones)} zones")
        except Exception as e:
            print(f"[ZONES] Error fetching HR zones: {e}")

        # Try to get power zones
        print("[ZONES] Fetching power zones...")
        power_zones = []
        try:
            # Power zones are typically trainer/power meter specific
            # Try to fetch from settings
            settings = api.get_user_settings()
            if "powerZones" in settings:
                power_zones = settings["powerZones"]
                print(f"[ZONES] Power zones found: {power_zones}")
        except Exception as e:
            print(f"[ZONES] Power zones not available: {e}")

        if power_zones:
            user.power_zones = power_zones

        db.commit()
        print("[ZONES] Profile sync completed")

    except Exception as e:
        print(f"[ZONES] Error syncing profile: {e}")


def sync_user_activities(
    db: Session,
    user_id: int,
    start_date: Optional[date] = None,
    end_date: Optional[date] = None,
) -> List[models.Workout]:
    """
    Sync activities from Garmin for a user.

    Args:
        db: Database session
        user_id: User ID
        start_date: Start date for sync (default: last 7 days, or 12 months if first sync)
        end_date: End date for sync (default: today)

    Returns:
        List of created Workout models
    """
    log_print(f"[GARMIN SYNC] Starting sync_user_activities for user {user_id}")
    logger.info(
        "Starting Garmin sync",
        extra={"user_id": user_id, "start_date": str(start_date), "end_date": str(end_date)}
    )

    # Get user to check if first sync
    user = crud.get_user_by_id(db, user_id)
    is_first_sync = user.last_garmin_sync is None
    log_print(f"[GARMIN SYNC] First sync: {is_first_sync}")

    # Get Garmin API
    logger.debug("Calling get_user_garmin_api", extra={"user_id": user_id})
    log_print(f"[GARMIN SYNC] Calling get_user_garmin_api...")
    try:
        api = get_user_garmin_api(db, user_id)
        log_print(f"[GARMIN SYNC] [OK] Garmin API obtained successfully")
        logger.debug("Garmin API obtained successfully", extra={"user_id": user_id})
    except Exception as e:
        log_print(f"[GARMIN SYNC] [ERROR] Failed to get Garmin API: {str(e)}")
        import traceback
        log_print(f"[GARMIN SYNC] Traceback:\n{traceback.format_exc()}")
        raise

    # #region agent log
    # Verify garth state BEFORE sync_user_zones_and_profile - DETAILED DIAGNOSTIC
    log_print(f"[GARMIN SYNC] [DIAGNOSTIC] Verifying state BEFORE sync_user_zones_and_profile...", hypothesis_id="H5", data={"step": "before_sync_profile_diagnostic"})
    try:
        global_client_before = hasattr(garth, 'client') and garth.client is not None
        global_oauth1_before = global_client_before and hasattr(garth.client, 'oauth1_token') and garth.client.oauth1_token is not None
        global_oauth2_before = global_client_before and hasattr(garth.client, 'oauth2_token') and garth.client.oauth2_token is not None
        global_client_id_before = id(garth.client) if global_client_before else None
        
        api_garth_exists_before = hasattr(api, 'garth')
        api_client_before = api_garth_exists_before and hasattr(api.garth, 'client') and api.garth.client is not None
        api_oauth1_before = api_client_before and hasattr(api.garth.client, 'oauth1_token') and api.garth.client.oauth1_token is not None
        api_oauth2_before = api_client_before and hasattr(api.garth.client, 'oauth2_token') and api.garth.client.oauth2_token is not None
        api_client_id_before = id(api.garth.client) if api_client_before else None
        
        log_print(f"[GARMIN SYNC] [DIAGNOSTIC] BEFORE sync_user_zones_and_profile:", hypothesis_id="H5", data={
            "global_client": global_client_before,
            "global_oauth1": global_oauth1_before,
            "global_oauth2": global_oauth2_before,
            "global_client_id": global_client_id_before,
            "api_client": api_client_before,
            "api_oauth1": api_oauth1_before,
            "api_oauth2": api_oauth2_before,
            "api_client_id": api_client_id_before,
            "same_object": global_client_id_before == api_client_id_before if (global_client_before and api_client_before) else False
        })
    except Exception as e:
        import traceback
        log_print(f"[GARMIN SYNC] [DIAGNOSTIC] Error checking state before sync_user_zones_and_profile: {str(e)}", level="error", hypothesis_id="H5", data={"error": str(e), "traceback": traceback.format_exc()})
    # #endregion
    
    # Sync user profile, zones, and settings
    # #region agent log
    log_print(f"[GARMIN SYNC] Calling sync_user_zones_and_profile...", hypothesis_id="H5", data={"step": "before_sync_profile"})
    # #endregion
    try:
        sync_user_zones_and_profile(db, user_id, api)
        # #region agent log
        log_print(f"[GARMIN SYNC] sync_user_zones_and_profile completed", hypothesis_id="H5", data={"step": "after_sync_profile"})
        # #endregion
    except Exception as e:
        # #region agent log
        log_print(f"[GARMIN SYNC] [ERROR] sync_user_zones_and_profile failed: {str(e)}", level="error", hypothesis_id="H5", data={"error": str(e)})
        # #endregion
        raise
    
    # #region agent log
    # Verify garth state AFTER sync_user_zones_and_profile - DETAILED DIAGNOSTIC
    log_print(f"[GARMIN SYNC] [DIAGNOSTIC] Verifying state AFTER sync_user_zones_and_profile...", hypothesis_id="H5", data={"step": "after_sync_profile_diagnostic"})
    try:
        global_client_after = hasattr(garth, 'client') and garth.client is not None
        global_oauth1_after = global_client_after and hasattr(garth.client, 'oauth1_token') and garth.client.oauth1_token is not None
        global_oauth2_after = global_client_after and hasattr(garth.client, 'oauth2_token') and garth.client.oauth2_token is not None
        global_client_id_after = id(garth.client) if global_client_after else None
        
        api_garth_exists_after = hasattr(api, 'garth')
        api_client_after = api_garth_exists_after and hasattr(api.garth, 'client') and api.garth.client is not None
        api_oauth1_after = api_client_after and hasattr(api.garth.client, 'oauth1_token') and api.garth.client.oauth1_token is not None
        api_oauth2_after = api_client_after and hasattr(api.garth.client, 'oauth2_token') and api.garth.client.oauth2_token is not None
        api_client_id_after = id(api.garth.client) if api_client_after else None
        
        # Check if state changed
        state_changed = False
        if global_client_before and global_client_after:
            state_changed = (global_client_id_before != global_client_id_after) or \
                          (global_oauth1_before != global_oauth1_after) or \
                          (api_oauth1_before != api_oauth1_after)
        
        log_print(f"[GARMIN SYNC] [DIAGNOSTIC] AFTER sync_user_zones_and_profile:", hypothesis_id="H5", data={
            "global_client": global_client_after,
            "global_oauth1": global_oauth1_after,
            "global_oauth2": global_oauth2_after,
            "global_client_id": global_client_id_after,
            "api_client": api_client_after,
            "api_oauth1": api_oauth1_after,
            "api_oauth2": api_oauth2_after,
            "api_client_id": api_client_id_after,
            "same_object": global_client_id_after == api_client_id_after if (global_client_after and api_client_after) else False,
            "state_changed": state_changed
        })
        
        if state_changed:
            log_print(f"[GARMIN SYNC] [DIAGNOSTIC] [WARNING] State changed after sync_user_zones_and_profile()!", level="warning", hypothesis_id="H5")
    except Exception as e:
        import traceback
        log_print(f"[GARMIN SYNC] [DIAGNOSTIC] Error checking state after sync_user_zones_and_profile: {str(e)}", level="error", hypothesis_id="H5", data={"error": str(e), "traceback": traceback.format_exc()})
    # #endregion

    # Default date range
    if not end_date:
        end_date = date.today()
    if not start_date:
        if is_first_sync:
            # First sync: get last 2 years
            start_date = end_date - timedelta(days=730)
            logger.info("First sync detected - pulling 2 years of history", extra={"user_id": user_id})
        else:
            # Subsequent syncs: from last sync date
            if user.last_garmin_sync:
                start_date = user.last_garmin_sync.date()
            else:
                start_date = end_date - timedelta(days=30)
            logger.info(f"Incremental sync from {start_date}", extra={"user_id": user_id, "start_date": str(start_date)})

    # #region agent log
    # CRITICAL FIX: Ensure api.garth.client has tokens before get_activities()
    # The issue is that api.garth.client might be a different object or not have tokens
    # We need to sync tokens from global garth.client to api.garth.client
    log_print(f"[GARMIN SYNC] [DIAGNOSTIC] Starting token verification before get_activities()...", hypothesis_id="H2", data={"step": "start_verification"})
    try:
        log_print(f"[GARMIN SYNC] [DIAGNOSTIC] Inside try block, checking garth state...", hypothesis_id="H2", data={"step": "inside_try"})
        global_client_before = hasattr(garth, 'client') and garth.client
        global_oauth1_before = global_client_before and hasattr(garth.client, 'oauth1_token') and garth.client.oauth1_token
        api_garth_exists = hasattr(api, 'garth')
        api_client_before = api_garth_exists and hasattr(api.garth, 'client') and api.garth.client
        api_oauth1_before = api_client_before and hasattr(api.garth.client, 'oauth1_token') and api.garth.client.oauth1_token
        
        log_print(f"[GARMIN SYNC] BEFORE get_activities() - global garth.client exists: {global_client_before}, has oauth1: {global_oauth1_before}, api.garth.client exists: {api_client_before}, has oauth1: {api_oauth1_before}", hypothesis_id="H2", data={"global_client": global_client_before, "global_oauth1": global_oauth1_before, "api_client": api_client_before, "api_oauth1": api_oauth1_before})
        
        # CRITICAL FIX: If api.garth.client doesn't have oauth1_token but global does, copy tokens
        if global_oauth1_before and api_client_before and not api_oauth1_before:
            log_print(f"[GARMIN SYNC] [FIX] api.garth.client missing oauth1_token, copying from global garth.client...", hypothesis_id="H2", data={"step": "copy_tokens"})
            try:
                # Copy oauth1 tokens
                if hasattr(garth.client, 'oauth1_token'):
                    api.garth.client.oauth1_token = garth.client.oauth1_token
                if hasattr(garth.client, 'oauth1_token_secret'):
                    api.garth.client.oauth1_token_secret = garth.client.oauth1_token_secret
                # Copy oauth2 tokens
                if hasattr(garth.client, 'oauth2_token'):
                    api.garth.client.oauth2_token = garth.client.oauth2_token
                if hasattr(garth.client, 'oauth2_token_secret'):
                    api.garth.client.oauth2_token_secret = getattr(garth.client, 'oauth2_token_secret', None)
                
                # Verify tokens were copied
                api_oauth1_after_copy = hasattr(api.garth.client, 'oauth1_token') and api.garth.client.oauth1_token
                log_print(f"[GARMIN SYNC] [FIX] Tokens copied, api.garth.client.oauth1_token exists: {api_oauth1_after_copy}", hypothesis_id="H2", data={"api_oauth1_after_copy": api_oauth1_after_copy})
            except Exception as copy_error:
                log_print(f"[GARMIN SYNC] [ERROR] Failed to copy tokens: {str(copy_error)}", level="error", hypothesis_id="H2")
        elif not api_client_before and global_client_before:
            # If api.garth.client doesn't exist, try to assign global client
            log_print(f"[GARMIN SYNC] [FIX] api.garth.client doesn't exist, assigning global garth.client...", hypothesis_id="H2", data={"step": "assign_client"})
            try:
                if hasattr(api, 'garth'):
                    api.garth.client = garth.client
                    # Also copy tokens to api.garth directly
                    if hasattr(garth.client, 'oauth1_token'):
                        api.garth.oauth1_token = garth.client.oauth1_token
                    if hasattr(garth.client, 'oauth1_token_secret'):
                        api.garth.oauth1_token_secret = garth.client.oauth1_token_secret
                    if hasattr(garth.client, 'oauth2_token'):
                        api.garth.oauth2_token = garth.client.oauth2_token
                    log_print(f"[GARMIN SYNC] [FIX] Assigned global garth.client to api.garth.client and copied tokens to api.garth", hypothesis_id="H2")
            except Exception as assign_error:
                log_print(f"[GARMIN SYNC] [ERROR] Failed to assign client: {str(assign_error)}", level="error", hypothesis_id="H2")
        
        # Check if api.garth.client is the same object as garth.client
        if global_client_before and api_client_before:
            same_client = garth.client is api.garth.client
            log_print(f"[GARMIN SYNC] garth.client and api.garth.client are same object: {same_client}", hypothesis_id="H3", data={"same_client": same_client})
        
        # CRITICAL FIX: api.garth.connectapi() uses api.garth.oauth1_token directly, not api.garth.client.oauth1_token
        # The traceback shows: self.garth.connectapi() -> self.request() -> assert self.oauth1_token
        # So we need to copy tokens to api.garth itself ALWAYS, regardless of current state
        if api_garth_exists and global_oauth1_before:
            log_print(f"[GARMIN SYNC] [FIX] Ensuring api.garth has oauth1_token (connectapi() uses api.garth.oauth1_token directly)...", hypothesis_id="H2", data={"step": "copy_to_garth_direct"})
            try:
                # ALWAYS copy tokens to api.garth directly (even if they seem to exist)
                # This ensures api.garth.oauth1_token is set for connectapi() calls
                if hasattr(garth.client, 'oauth1_token') and garth.client.oauth1_token:
                    api.garth.oauth1_token = garth.client.oauth1_token
                    log_print(f"[GARMIN SYNC] [FIX] Copied oauth1_token to api.garth", hypothesis_id="H2")
                if hasattr(garth.client, 'oauth1_token_secret') and garth.client.oauth1_token_secret:
                    api.garth.oauth1_token_secret = garth.client.oauth1_token_secret
                if hasattr(garth.client, 'oauth2_token') and garth.client.oauth2_token:
                    api.garth.oauth2_token = garth.client.oauth2_token
                
                # Verify
                api_garth_oauth1_after = hasattr(api.garth, 'oauth1_token') and api.garth.oauth1_token is not None
                log_print(f"[GARMIN SYNC] [FIX] Verification - api.garth.oauth1_token exists: {api_garth_oauth1_after}", hypothesis_id="H2", data={"api_garth_oauth1": api_garth_oauth1_after})
                
                if not api_garth_oauth1_after:
                    log_print(f"[GARMIN SYNC] [ERROR] Failed to set api.garth.oauth1_token!", level="error", hypothesis_id="H2")
            except Exception as copy_error:
                import traceback
                log_print(f"[GARMIN SYNC] [ERROR] Failed to copy tokens to api.garth: {str(copy_error)}", level="error", hypothesis_id="H2", data={"error": str(copy_error), "traceback": traceback.format_exc()})
    except Exception as e:
        import traceback
        log_print(f"[GARMIN SYNC] Error checking/fixing state before get_activities(): {str(e)}", level="error", hypothesis_id="H2", data={"error": str(e), "traceback": traceback.format_exc()})
    # #endregion

    # Fetch activities with high limit to get all activities
    # Note: get_activities() is more reliable than get_activities_by_date() which has internal limits
    # #region agent log
    log_print(f"[GARMIN SYNC] Calling api.get_activities(start=0, limit=1000)...", hypothesis_id="H2", data={"step": "before_get_activities"})
    # #endregion
    try:
        activities = api.get_activities(start=0, limit=1000)
        # #region agent log
        log_print(f"[GARMIN SYNC] [OK] api.get_activities() succeeded, got {len(activities)} activities", hypothesis_id="H2", data={"activity_count": len(activities)})
        # #endregion
    except Exception as e:
        import traceback
        traceback_str = traceback.format_exc()
        # #region agent log
        log_print(f"[GARMIN SYNC] [ERROR] api.get_activities() failed: {str(e)}", level="error", hypothesis_id="H2", data={"error": str(e), "error_type": type(e).__name__, "traceback": traceback_str})
        
        # Check state AFTER error
        try:
            global_client_after = hasattr(garth, 'client') and garth.client
            global_oauth1_after = global_client_after and hasattr(garth.client, 'oauth1_token') and garth.client.oauth1_token
            api_client_after = hasattr(api, 'garth') and hasattr(api.garth, 'client') and api.garth.client
            api_oauth1_after = api_client_after and hasattr(api.garth.client, 'oauth1_token') and api.garth.client.oauth1_token
            log_print(f"[GARMIN SYNC] AFTER get_activities() ERROR - global garth.client exists: {global_client_after}, has oauth1: {global_oauth1_after}, api.garth.client exists: {api_client_after}, has oauth1: {api_oauth1_after}", hypothesis_id="H2", data={"global_client": global_client_after, "global_oauth1": global_oauth1_after, "api_client": api_client_after, "api_oauth1": api_oauth1_after})
        except:
            pass
        # #endregion
        raise

    # Filter by date range
    activities = [
        act
        for act in activities
        if start_date <= date.fromisoformat(act["startTimeLocal"][:10]) <= end_date
    ]

    logger.info(
        f"Found {len(activities)} activities from Garmin in date range",
        extra={"user_id": user_id, "activity_count": len(activities)}
    )

    created_workouts = []
    skipped_count = 0
    max_to_import = 1000  # Safety limit (increased for initial sync)

    for activity_dict in activities:
        # Stop if we reach 1000 workouts
        if len(created_workouts) + skipped_count >= max_to_import:
            logger.warning(
                f"Reached max import limit of {max_to_import}",
                extra={"user_id": user_id, "max_limit": max_to_import}
            )
            break

        activity_type = activity_dict.get("activityType", {}).get("typeKey", "")

        # Only process running activities
        if "running" not in activity_type.lower():
            skipped_count += 1
            continue

        activity_id = str(activity_dict["activityId"])

        try:
            # Download FIT file
            zip_data = api.download_activity(
                activity_id, dl_fmt=api.ActivityDownloadFormat.ORIGINAL
            )

            # Extract FIT from ZIP
            with zipfile.ZipFile(io.BytesIO(zip_data), "r") as zip_ref:
                fit_filename = [
                    name for name in zip_ref.namelist() if name.endswith(".fit")
                ][0]
                with zip_ref.open(fit_filename) as fit_file:
                    fit_data = fit_file.read()

            # Parse FIT
            workout_data = parse_fit_file(fit_data, activity_id)

            # Log running dynamics data for debugging
            print(
                f"[DEBUG] Parsed workout data - Cadence: {workout_data.get('avg_cadence')}, "
                f"VO: {workout_data.get('avg_vertical_oscillation')}, "
                f"Stance: {workout_data.get('avg_stance_time')}, "
                f"Balance: {workout_data.get('left_right_balance')}"
            )

            # Check if already exists by start_time (more reliable than ID)
            existing = crud.get_workout_by_start_time(
                db, user_id, workout_data["start_time"]
            )
            if existing:
                print(
                    f"[SYNC] Workout at {workout_data['start_time']} already exists, skipping"
                )
                skipped_count += 1
                continue

            # Create workout schema
            from ..schemas import WorkoutCreate

            workout_create = WorkoutCreate(**workout_data)

            # Log what's being passed to the database
            print(
                f"[DEBUG] WorkoutCreate object - Cadence: {workout_create.avg_cadence}, "
                f"VO: {workout_create.avg_vertical_oscillation}"
            )

            # Save to database
            workout = crud.create_workout(db, user_id, workout_create)
            created_workouts.append(workout)

        except Exception as e:
            print(f"Error processing activity {activity_id}: {e}")
            skipped_count += 1
            continue

    # Update last_garmin_sync timestamp
    user.last_garmin_sync = datetime.utcnow()
    db.commit()

    print(
        f"[SYNC] Completed. Created: {len(created_workouts)}, Skipped: {skipped_count}"
    )
    return created_workouts


def sync_garmin_activities(db: Session, user_id: int) -> List[models.Workout]:
    """
    Fetch recent activities from Garmin, parse them, and store them.
    """
    print("[SYNC] Starting sync...")
    try:
        api = get_user_garmin_api(db, user_id)
        print("[SYNC] API obtained successfully")

        # Sync user profile data (HR zones, etc.) first
        sync_user_profile_data(db, user_id, api)

        # Determine date range for fetching activities
        user = crud.get_user_by_id(db, user_id)
        is_first_sync = user.last_garmin_sync is None
        end_date = date.today()

        # First sync: get last 2 years (730 days)
        # Subsequent syncs: get from last sync date (not last workout date!)
        if is_first_sync:
            start_date = end_date - timedelta(days=730)
            print(f"[SYNC] First sync detected - pulling 2 years of history")
        else:
            # Use last_garmin_sync date (when we last checked), not last workout date
            # This ensures we don't miss workouts if user hasn't synced in a while
            if user.last_garmin_sync:
                start_date = user.last_garmin_sync.date()
            else:
                # Fallback: get last 30 days if somehow sync date is missing
                start_date = end_date - timedelta(days=30)
            print(f"[SYNC] Incremental sync from last sync: {start_date}")

        print(f"[SYNC] Fetching activities from {start_date} to {end_date}")

        # Fetch activities with high limit to get all activities
        activities = api.get_activities(start=0, limit=1000)

        # Filter by date range
        activities = [
            act
            for act in activities
            if start_date <= date.fromisoformat(act["startTimeLocal"][:10]) <= end_date
        ]

        print(f"[SYNC] Found {len(activities)} activities from Garmin in date range")

        created_workouts = []
        skipped_count = 0
        max_to_import = 1000  # Safety limit (increased for initial sync)

        for activity_dict in activities:
            # Stop if we reach 1000 workouts
            if len(created_workouts) + skipped_count >= max_to_import:
                logger.warning(
                f"Reached max import limit of {max_to_import}",
                extra={"user_id": user_id, "max_limit": max_to_import}
            )
                break

            activity_type = activity_dict.get("activityType", {}).get("typeKey", "")

            # Only process running activities
            if "running" not in activity_type.lower():
                skipped_count += 1
                continue

            activity_id = str(activity_dict["activityId"])

            try:
                # Download FIT file
                zip_data = api.download_activity(
                    activity_id, dl_fmt=api.ActivityDownloadFormat.ORIGINAL
                )

                # Extract FIT from ZIP
                with zipfile.ZipFile(io.BytesIO(zip_data), "r") as zip_ref:
                    fit_filename = [
                        name for name in zip_ref.namelist() if name.endswith(".fit")
                    ][0]
                    with zip_ref.open(fit_filename) as fit_file:
                        fit_data = fit_file.read()

                # Parse FIT
                workout_data = parse_fit_file(fit_data, activity_id)

                # Log running dynamics data for debugging
                print(
                    f"[DEBUG] Parsed workout data - Cadence: {workout_data.get('avg_cadence')}, "
                    f"VO: {workout_data.get('avg_vertical_oscillation')}, "
                    f"Stance: {workout_data.get('avg_stance_time')}, "
                    f"Balance: {workout_data.get('left_right_balance')}"
                )

                # Check if already exists by start_time (more reliable than ID)
                existing = crud.get_workout_by_start_time(
                    db, user_id, workout_data["start_time"]
                )
                if existing:
                    print(
                        f"[SYNC] Workout at {workout_data['start_time']} already exists, skipping"
                    )
                    skipped_count += 1
                    continue

                # Create workout schema
                from ..schemas import WorkoutCreate

                workout_create = WorkoutCreate(**workout_data)

                # Log what's being passed to the database
                print(
                    f"[DEBUG] WorkoutCreate object - Cadence: {workout_create.avg_cadence}, "
                    f"VO: {workout_create.avg_vertical_oscillation}"
                )

                # Save to database
                workout = crud.create_workout(db, user_id, workout_create)
                created_workouts.append(workout)

            except Exception as e:
                logger.warning(
                    f"Error processing activity {activity_id}",
                    extra={"user_id": user_id, "activity_id": activity_id, "error": str(e)},
                    exc_info=True
                )
                skipped_count += 1
                continue

        # Update last_garmin_sync timestamp
        user.last_garmin_sync = datetime.utcnow()
        db.commit()

        logger.info(
            f"Garmin sync completed. Created: {len(created_workouts)}, Skipped: {skipped_count}",
            extra={
                "user_id": user_id,
                "created_count": len(created_workouts),
                "skipped_count": skipped_count,
            }
        )
        return created_workouts
    except Exception as e:
        logger.error(
            "Error during Garmin sync",
            extra={"user_id": user_id, "error": str(e)},
            exc_info=True
        )
        return []
